In [3]:
import numpy as np
import pandas as pd
from keras.models import load_model
from matplotlib import pyplot as plt
import os
from sklearn.preprocessing import MinMaxScaler
from keras.utils import np_utils
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


if __name__ == '__main__':

    #           PARAMS           #
    input_data_length = 30
    model_num = '64'
    crop_size = input_data_length
    check_span = 40    
    
    dir = './Made_Chart_to_np/%s_%s/' % (input_data_length, model_num)
    np_list = os.listdir(dir)

    #       Make folder      #
    try:
        os.mkdir('./pred_ohlcv/%s_%s/' % (input_data_length, model_num))
    except Exception as e:
        pass

    try:
        os.mkdir('./Figure_pred/%s_%s/' % (input_data_length, model_num))
    except Exception as e:
        pass

    except_list = os.listdir('./pred_ohlcv/%s_%s/' % (input_data_length, model_num))

    #       LOAD MODEL      #
    model = load_model('./model/rapid_ascending %s_%s_chart.hdf5' % (input_data_length, model_num))

    for file in np_list:

        #         if file in except_list:
        #             continue

        print('loading %s' % file)

        Date = file.split('_')[0]
        Coin = file.split('_')[1].split('.')[0]

        try:
            X_test = np.load('./Made_Chart_to_np/%s_%s/%s' % (input_data_length, model_num, file)).astype(np.float32) / 255.
            # X_test = X_test[:100]
            print(X_test.shape)
            # quit()

            row = X_test.shape[1]
            col = X_test.shape[2]

        except Exception as e:
            print('Error in getting data from made_x :', e)
            continue

        if X_test is not None:
            if len(X_test) != 0:

                Y_pred_ = model.predict(X_test, verbose=1)

                min_value = np.min(Y_pred_, axis=0)
                print(min_value)
                # print(Y_pred_)
                Y_pred = np.argmax(Y_pred_, axis=1)
#                 Y_pred = np.zeros(len(Y_pred_))
#                 for i in range(len(Y_pred_)):
#                     if Y_pred_[i][0] < 1.14e-15:
#                         Y_pred[i] = 1
#                     if Y_pred_out_[i][0] < 1.15e-18:
#                         Y_pred[i] = 2

                spanlist_low = []
                spanlist_high = []

                for m in range(len(Y_pred)):
                    if (Y_pred[m] > 0.5) and (Y_pred[m] < 1.5):
                        if m + 1 < len(Y_pred):
                            spanlist_low.append((m, m + 1))
                        else:
                            spanlist_low.append((m - 1, m))

                for m in range(len(Y_pred)):
                    if (Y_pred[m] > 1.5) and (Y_pred[m] < 2.5):
                        if m + 1 < len(Y_pred):
                            spanlist_high.append((m, m + 1))
                        else:
                            spanlist_high.append((m - 1, m))

                ohlcv_excel = pd.read_excel('./ohlcv/%s %s ohlcv.xlsx' % (Date, Coin), index_col=0)
                ohlcv_excel['MA60'] = ohlcv_excel['close'].rolling(60).mean()
                ohlcv_data = ohlcv_excel.values[sum(ohlcv_excel.MA60.isna()): -check_span].astype(np.float)[crop_size:]

                plt.subplot(211)
                # plt.subplot(313)
                plt.plot((ohlcv_data[:, [1]]), 'gold', label='close')
                plt.plot((ohlcv_data[:, [5]]), 'b', label='ma')
                plt.legend(loc='upper right')
                for i in range(len(spanlist_low)):
                    plt.axvspan(spanlist_low[i][0], spanlist_low[i][1], facecolor='c', alpha=0.7)

                plt.subplot(212)
                # plt.subplot(313)
                plt.plot((ohlcv_data[:, [1]]), 'gold', label='close')
                plt.plot((ohlcv_data[:, [5]]), 'b', label='ma')
                plt.legend(loc='upper right')
                for i in range(len(spanlist_high)):
                    plt.axvspan(spanlist_high[i][0], spanlist_high[i][1], facecolor='m', alpha=0.7)

                plt.savefig('./Figure_pred/%s_%s/%s %s.png' % (input_data_length, model_num, Date, Coin), dpi=500)
                plt.close()







loading 2020-01-11_BTT.npy
(5, 300, 300, 3)
5/5 [==============================] - 0s 39ms/step
[1.0000000e+00 1.2619692e-23 1.6087427e-29]
loading 2020-01-11_FX.npy
(274, 300, 300, 3)
274/274 [==============================] - 1s 4ms/step
[0.999782 0.       0.      ]
loading 2020-01-12_BTG.npy
Error in getting data from made_x : cannot reshape array of size 0 into shape (862,300,300,3)
loading 2020-01-12_BAT.npy
(8, 300, 300, 3)
8/8 [==============================] - 0s 4ms/step
[1.0000000e+00 8.2514910e-29 3.6616406e-25]
loading 2020-01-11_ABT.npy
(28, 300, 300, 3)
28/28 [==============================] - 0s 4ms/step
[1.0000000e+00 1.4481097e-36 6.5707247e-33]
loading 2020-01-11_ELF.npy
(62, 300, 300, 3)
62/62 [==============================] - 0s 5ms/step
[9.9988842e-01 0.0000000e+00 1.1362825e-37]
loading 2020-01-11_LINK.npy
(442, 300, 300, 3)
442/442 [==============================] - 2s 5ms/step
[3.9120486e-19 0.0000000e+00 0.0000000e+00]
loading 2020-01-11_MCO.npy
(0,)
Error in 

88/88 [==============================] - 0s 5ms/step
[2.0376679e-06 0.0000000e+00 0.0000000e+00]
loading 2020-01-11_ETH.npy
(1024, 300, 300, 3)
1024/1024 [==============================] - 4s 4ms/step
[2.1408621e-13 0.0000000e+00 0.0000000e+00]
loading 2020-01-11_ZRX.npy
(22, 300, 300, 3)
22/22 [==============================] - 0s 4ms/step
[9.9992156e-01 1.6463560e-25 4.3397032e-26]
loading 2020-01-11_ZIL.npy
(0,)
Error in getting data from made_x : tuple index out of range
loading 2020-01-11_AMO.npy
(652, 300, 300, 3)
652/652 [==============================] - 3s 5ms/step
[7.447417e-07 0.000000e+00 0.000000e+00]
loading 2020-01-11_BSV.npy
(685, 300, 300, 3)
685/685 [==============================] - 3s 5ms/step
[3.6758485e-16 0.0000000e+00 0.0000000e+00]
loading 2020-01-11_LUNA.npy
(1054, 300, 300, 3)
1054/1054 [==============================] - 5s 5ms/step
[1.001686e-18 0.000000e+00 0.000000e+00]
loading 2020-01-11_VALOR.npy
(70, 300, 300, 3)
70/70 [==============================] -